services:
  django_migrations:
    restart: on-failure
    depends_on:
      - db
    build: .
    command: python manage.py migrate
    env_file:
      - '.env'
  django:
    restart: always
    depends_on:
      - django_migrations
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - '.env'
  db:
    image: "postgres"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - '.env'