openapi: 3.0.3
info:
  title: Bookstore
  description: Bookstore page
  version: 1.0.0
servers:
  - url: https://bookstore0-80ca638e1301.herokuapp.com/api
paths:
  /books:
    post:
      summary: Add book
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BooksAdd'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksGet'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
components:
  schemas:
    BooksAdd:
      type: object
      required:
        - title
        - author
        - genre
        - publication_date
      properties:
        title:
          type: string
          description: book title
          example: test_book
        author:
          type: string
          description: book author
          example: test_author
        genre:
          type: string
          description: book genre
          example: test_genre
        publication_date:
          type: string
          description: book publication_date
          example: test_publication_date
    BooksGet:
      type: object
      required:
        - id
        - msg
      properties:
        id:
          type: integer
          description: book id
          example: 1
        msg:
          type: string
          description: info msg
          example: book added successfully