name: tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      MEMCACHIER_SERVERS: ${{ secrets.MEMCACHIER_SERVERS }}
      MEMCACHIER_USERNAME: ${{ secrets.MEMCACHIER_USERNAME }}
      MEMCACHIER_PASSWORD: ${{ secrets.MEMCACHIER_PASSWORD }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@master
      - name: run tests
        run: |
          pip install -r requirements.txt
          pytest